apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ygqa
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0031-tenant/tkrw-pr712-0075-0031-app/devfile-sample-ygqa@sha256:12cf55ef7d6409a77dec3d261beff3c3c20071c4782c55f9c471123cfb034cdd
        name: my-nodejs
        resources: {}
status: {}
